# Generated by Django 5.0 on 2024-01-27 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reaction',
            name='bayildim_count',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='kizgin_count',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='komik_count',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='saskin_count',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='uzgun_count',
        ),
        migrations.AddField(
            model_name='reaction',
            name='reaction_type',
            field=models.CharField(choices=[('bayildim', 'Bayıldım'), ('komik', 'Komik'), ('saskin', 'Şaşkın'), ('uzgun', 'Üzgün'), ('kizgin', 'Kızgın')], default='1', max_length=20),
            preserve_default=False,
        ),
    ]
