# Generated by Django 5.0 on 2024-01-27 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_reaction_bayildim_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
