# Generated by Django 5.0 on 2024-01-27 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_reaction_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reaction',
            name='count',
        ),
    ]
