# Generated by Django 5.0 on 2024-01-27 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_reaction_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reaction',
            old_name='count',
            new_name='bayildim_count',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='reaction_type',
        ),
        migrations.AddField(
            model_name='reaction',
            name='kizgin_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reaction',
            name='komik_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reaction',
            name='saskin_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reaction',
            name='uzgun_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
