# Generated by Django 5.0 on 2024-01-27 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_reaction_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reaction',
            name='bayildim_count',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='kizgin_count',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='komik_count',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='saskin_count',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='uzgun_count',
        ),
        migrations.AddField(
            model_name='reaction',
            name='reaction_type',
            field=models.CharField(blank=True, choices=[('bayildim', 'Bayıldım'), ('komik', 'Komik'), ('saskin', 'Şaşkın'), ('uzgun', 'Üzgün'), ('kizgin', 'Kızgın')], max_length=20, null=True),
        ),
    ]
