# Generated by Django 5.0 on 2024-01-27 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_reaction_bayildim_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='reaction_type',
            field=models.CharField(choices=[('bayildim', 'Bayıldım'), ('komik', 'Komik'), ('saskin', 'Şaşkın'), ('uzgun', 'Üzgün'), ('kizgin', 'Kızgın')], default='1', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reaction',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
